TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../src/tt_um_francisco.v ../src/alu_8bit.v ../src/carry_lookahead_adder_8bit.v
TOPLEVEL = tt_um_francisco
MODULE = test_user_module

include $(shell cocotb-config --makefiles)/Makefile.sim

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
